config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
   validates :content, presence: true
   belongs_to :user, optional: true
   has_many :favorite_users, through: :favorites, source: :user
   has_many :favorites, dependent: :destroy
   mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :pictures
  has_many :favorites, dependent: :destroy
  mount_uploader :user_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @rrent_usercu == nil
    redirect_to("/login")
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorite = current_user.favorites
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user,{only:[:edit, :update, :destroy]}

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
      @picture = current_user.pictures.build(picture_params)
      if params[:back]
        render :new
      else
        if @picture.save
          PictureMailer.picture_mail(@picture).deliver
          redirect_to pictures_path, notice: "投稿を作成しました"
        else
          render 'new'
        end
      end
    end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "編集しました"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "削除しました"
  end

  def confirm
    @picture = Picture.new(picture_params)
    render :new if @picture.invalid?
  end

  def ensure_correct_user
    if @picture.user.id != current_user.id 
      flash[:notice] = "権限がありません"
      redirect_to pictures_path
    end
  end

  private

  def picture_params
    params.require(:picture).permit( :image, :content, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :ensure_correct_user,{only:[:edit, :update, :destroy]}
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(session[:user_id])
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "画像を登録しました"
    else
      render 'edit'
    end
  end

  def edit
  end

  def show
  end
  
  def ensure_correct_user
    if @user.id != current_user.id 
      flash[:notice] = "権限がありません"
      redirect_to pictures_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_image, :user_image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>

<div class="favorites_contents">
  <% @favorite.each do |favorite| %>

  <div class="index_picture">
    <div class="index_user_name">ユーザー名：<%= favorite.user.name %></div>
    <%= image_tag favorite.picture.image.url if favorite.picture.image.url %>
    <div class=""><%= favorite.picture.content if favorite.picture.content %></div>
  </div>
  <br>
  <% end %>

  <%= link_to "マイページへ", user_path(current_user) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>matsugram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
  </head>
  <body>
    <header>
      <div class="app_name"><%= link_to "MATSUGRAM", pictures_path %></div>
      <div class="header_manu">
        <% if logged_in? %>
        <div class="profile"><%= link_to "マイページ", user_path(current_user.id) %></div>
        <div class="new_post"><%= link_to "投稿一覽", pictures_path %></div>
        <div class="new_post"><%= link_to "投稿画面", new_picture_path %></div>
        <div class="new_post"><%= link_to "お気に入り一覽", favorites_path %></div>
        <div class="logout"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></div>
        <div class="crrent_user">ユーザー名：<%= current_user.name %></div>
        <% else %>
        <div class="sign_up"><%= link_to "新規登録", new_user_path %></div>
        <div class="login"><%= link_to "ログイン", new_session_path %></div>
        <% end %>
      </div>
    </header>
    <% flash.each do |key,value| %>
    <%= content_tag(:div,value,class:"#{key}")%>
    <% end %>
        <%= yield %>
        <footer>
          <div>
            <li>MATSUGRAM</li>
            <li>© 2019 Copyright MATSUSE</li>
          </div>
        </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <br>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache%>
  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<%= link_to "一覧にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "投稿する" %>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache%>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '一覧ページへ', pictures_path %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>


  <div class="contents">
    <% @pictures.each do |picture| %>
    <div class="index_picture">
      <div class="index_user_name">ユーザー名：<%= picture.user.name %></div>
      <%= image_tag picture.image.url if picture.image.url %>
      <div class=""><%= picture.content if picture.content %></div>
      <div class="index_picture_menu">
        <div class="index_show"><%= link_to '詳細', picture_path(picture.id) %></div>
        <% if current_user.id == picture.user.id %>
        <div class="index_edit"><%= link_to "編集", edit_picture_path(picture.id), data: { confirm: '本当に編集していいですか？' } %></div>
        <div class="index_destroy"><%= link_to '削除', picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></div>
        <% end %>
      </div>
    </div>
    <br>
    <% end %>
  </div>

app/views/pictures/new.html.erb
<h1>投稿画面</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>
<div class="show_image">
  <%= image_tag @picture.image.url if @picture.image.url %>
</div>
<div class="show_content">
  <%= @picture.content if @picture.content %>
</div>
  <div class="favorite">
    <% unless @picture.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
  <div class="edit_menu">
    <% if current_user.id == @picture.user.id %>
    <div class="show_edit"><%= link_to '編集', edit_picture_path %></div>
  </div>
<% end %>
<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/users/edit.html.erb
<h1>プロフィール画像設定</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <br>
    <%= form.file_field :user_image %>
    <%= form.hidden_field :user_image_cache%>
    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "マイページへ", user_path(current_user) %>

app/views/users/new.html.erb
<div class="main-container ">
<h1>新規登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %> 
  <%= f.email_field :email %>

  <%= f.label :user_image %>
  <%= f.file_field :user_image %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>
</div>

app/views/users/show.html.erb
<p>メールアドレス: <%= @user.email %></p>

<div class="show_image">
  <%= image_tag @user.user_image.url if @user.user_image.url %>
</div>

<% unless @user.id != current_user.id %>
<%= link_to "プロフィール画像設定", edit_user_path %>
<% end %>
<%= link_to "お気に入り一覧へ", favorites_path %>
<%= link_to "投稿一覧画面へ", pictures_path %>
<%= link_to "投稿する", new_picture_path %>